---
- name: Create directory for backup script
  file:
    path: '{{ item }}'
    state: directory
    group: adm
    mode: 0775
  with_items:
    - '{{ s3cmd_upload_script_dir }}'
    - '{{ s3cmd_upload_directory }}'

- name: Create backup script
  template:
    src: 'upload.sh.j2'
    dest: '{{ s3cmd_upload_script }}'
    mode: 0755
